Conversion enhancements
jesusgn90/nodemcu-examples pull request #7
Opened 2020-08-01 09:42 UTC by jorgemgn

2020-08-01 10:57 UTC, jesusgn90 requested changes
**About the code**

This is not well structured and is not well coded, here is a proposal:

Out of the loop function, define a new enum type with the different units:
```c
typedef enum {
    PA,
    HPA,
    ATM
} UNIT;
```

Now create a variable with the desired unit:
```c
UNIT unit = ATM;
```

Then, in the loop function:

```c
void loop () {
    float pressure = bmp280.readPressure(); // Defaults PA
    switch (unit) {
        case HPA: 
            pressure /= 100.0F;
            break;
        case ATM:
            pressure *= 0.0000102;
            break;
        // etc
    }
    Serial.print(pressure);
    delay(1000);
}
```

**About the PR**

- Do not use commits using the GitHub website, instead create local branch, test it, commit and push. Also if doing commits in the GitHub website, the CI I have configured is not being fired, it's only being fired on push, I have to fix it but please do as I describe.
- Add a PR description.

2020-08-01 21:59 UTC, jorgemgn commented
Code using enum type and switch, without displaying anything in serial.

     #include <Adafruit_BMP280.h>

     // Using 0x77 implies both CSB and SDO are connected to 3V3!
     #define BMP280_I2C_ADDRESS  0x77

     // initialize Adafruit BMP280 library
     Adafruit_BMP280  bmp280;

     typedef enum {Pa, hPa, atm, bar, Torr, mmWS, psi} UNIT; // Available measurement units

     UNIT unit = hPa; // Replace with the desired unit

     void setup()
     {
       Serial.begin(9600);
       delay(1000);

       /*
          SDA connected to NodeMCU D2 pin, which is GPIO4
          SCL connected to NodeMCU D1 pin, which is GPIO5
       */
       Wire.begin(4, 5);

       // initialize the BMP280 sensor
       while (bmp280.begin(BMP280_I2C_ADDRESS) == 0)
       { 
         // connection error or device address wrong!
         Serial.println("Could not initialize sensor, retrying now...");
         delay(1000);
       }
     }

     void loop()
     {
       float pressure = bmp280.readPressure();  // Defaults Pa

       switch (unit) {

         case hPa:
           pressure /= 100.0F;
           break;

         case atm:
           pressure *= 0.0000102F;
           break;

         case bar:
           pressure /= 100000;
           break;

         case Torr:
           pressure *= 0.0075;
           break;

         case mmWS:
           pressure *= 0.102;
           break;

         case psi:
           pressure *= 0.000145;
           break;
       }

     delay(1000);

     }

2020-08-02 08:25 UTC, jesusgn90 commented
Please use commit and push and not a comment so I can review the code properly

2020-08-03 21:13 UTC, jorgemgn commented
> Please use commit and push and not a comment so I can review the code properly

Sorry, [there's the commit](https://github.com/jesusgn90/nodemcu-examples/pull/7/commits/b315aac20c9e1b2d27286b6d161f4d0474f38869) with the requested modifications.

2026-07-12 06:40 UTC, closed without merging